server:
  port: 8089

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.juror.support.sql.controllers
  writer-with-order-by-keys: true
spring:
  config:
    import: "optional:configtree:/mnt/secrets/juror/"
  application:
    name: Juror SQL Support library
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:juror}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: JurorSqlSupportHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
          batch_size: 100
        format_sql: true
    show-sql: false
    generate-ddl: false
uk:
  gov:
    hmcts:
      juror:
        security:
          secret: ${JUROR_SECURITY_SECRET:W3N1cGVyLXNlY3JldC1rZXktYnVyZWF1XVtzdXBlci1zZWNyZXQta2V5LWJ1cmVhdV1bc3VwZXItc2VjcmV0LWtleS1idXJlYXVd}
azure:
  application-insights:
    instrumentation-key: ${juror.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
